### ISSUE TITLE
count_link_for_each_kind.pl cannot get gapped reads number

### ISSUE THREAD

**Issue by PonderLi** [caochch/RICpipe#3]
Hi, Cao:

Thanks for your great work! I met one problem when running the script  step1.collect_pair_tags/scripts/count_link_for_each_kind.pl, I cannot get the gapped number. After checking script, I found you define a subfunction to calculate gapped number:
sub part_count{
	my $file=shift;
	my $part_num;
	open(IN,$file) || die;
	while(my $line=<IN>){
		chomp $line;
		my @sub=split/\s+/,$line;
		if($sub[0] =~ /Part_from_Align_Read/){
			$part_num+=$sub[1];
		}
	}
	close IN;
	return $part_num;
}

This function aims to find the reads' name started with "Part_from_Align_Read" and sum the second column. But I have non reads which starts with "Part_from_Align_Read". The STAR vesion is 2.7.10b。 Only "Head" and "Tail" can be found at the beginning of reads' name. And I don't know what's the function of this subfunction, can it calculate the gapped reads number?
Looking forward to your reply

**Comment by caochch** [comment]
This subfunction read a file named "num_of_interactions_from_part.list" (i.e., the third parameter feed to this script).
This file should be like:
Part_from_Align_Read1:  9784600
Part_from_Align_Read2:  9373968
Part_from_Chimeric_Read1:       52472
Part_from_Chimeric_Read2:       49731
