### ISSUE TITLE
Speed of STAR aligner is extremely low

### ISSUE THREAD

**Issue by Wang-Taiwei** [caochch/RICpipe#5]
Hi cao,

Thanks for your great work! I met a question that when I mapped the reads to rRNA using STAR (2.5.3b) configuration the same as yours, the speed is less than 2 M/h and it takes several days and still not finish. I tried to change machines but it didn't work. The load of CPUs is full during the process. Is it normal for RIC-seq data with your configuration or I should check rRNA reference or STAR version or machine again ?

Thanks!

 Time    Speed        Read     Read   Mapped   Mapped   Mapped   Mapped Unmapped Unmapped Unmapped Unmapped
                    M/hr      number   length   unique   length   MMrate    multi   multi+       MM    short    other
Dec 05 05:02:03      0.2     1049165      128     1.7%    134.7     1.3%    21.6%     0.0%     0.0%    58.7%    18.0%
Dec 05 05:04:00      0.4     2092755      128     1.7%    134.6     1.4%    21.2%     0.0%     0.0%    59.1%    18.0%
Dec 05 05:07:15      0.5     3135946      128     1.6%    134.4     1.4%    21.0%     0.0%     0.0%    59.3%    18.1%
Dec 05 05:09:53      0.7     4178318      128     1.6%    134.4     1.4%    20.8%     0.0%     0.0%    59.5%    18.1%
Dec 05 05:11:31      1.0     6260778      128     1.6%    134.2     1.4%    20.5%     0.0%     0.0%    59.8%    18.2%
Dec 05 05:12:41      1.2     7302778      128     1.6%    134.1     1.5%    20.4%     0.0%     0.0%    59.8%    18.2%
Dec 05 05:13:41      1.5     9378538      128     1.6%    134.2     1.5%    20.2%     0.0%     0.0%    60.0%    18.2%

**Comment by Wang-Taiwei** [comment]
A possible reason is low mappability for rRNA reference. For STAR tool, it may be a useful way to increase speed by reducing `--seedPerWindowNmax`. Did you change this parameter when aligning ?

**Comment by caochch** [comment]
It is correct. STAR tries hard to find possible hits for each read, so its speed becomes very slow when the mapping rate is low. It is fine. I did not set the seedPerWindowNmax, but I think it is not so related.

**Comment by Wang-Taiwei** [comment]
I tried to set `--seedPerWindowNmax` from default to 10 and the speed has increased by dozens of times. I think 20 may be a balance between speed and sensitivity. Thank you for your reply! And it may be helpful to others who meet the same issues.
