### ISSUE TITLE
How to prepare the gene annotation files

### ISSUE THREAD

**Issue by ZHIDIHUAYUAN** [caochch/RICpipe#6]
Hi,
Thank you for providing this nice pipeline for RIC data analysis.
I have some trouble in preparing gene annotation files. I use the reference hg38. How can I get the hg19.integrated.NCExon.bed.gz hg19.integrated.NCIntron.bed.gz hg19.integrated.PC3UTR.bed.gz hg19.integrated.PC5UTR.bed.gz hg19.integrated.PCCDS.bed.gz hg19.integrated.PCIntron.bed.gz? which is the meaning of PC?
Thank you!

**Comment by caochch** [comment]
PC means protein-coding genes.
You can download the gtf files from the Gencode database and use Perl or
Python scripts to extract coordinates for exons, introns, or UTRs, with
help from BEDtools software.

ZHIDIHUAYUAN ***@***.***> 于2024年3月4日周一 11:09写道：

**Comment by ZHIDIHUAYUAN** [comment]
Thanks for your answer.
I still have another question. In the step3.category_intra_reads, there is a parameter called minimum_fragment_size. How can I decided this value? Do you have any suggestions?

Thank you!

**Comment by ZHIDIHUAYUAN** [comment]
Does it depend on the sequencing strategy? I noticed that in your database GSE190214, you used 2*150bp squencing library. What is the value of minimum_fragment_size you used?

**Comment by caochch** [comment]
It depends on the fragment size distribution and the largest fragment size
in normal RNA-seq libraries. I used 600 by default. Lower values may
result in more 'false-positive chimeric' paired-end reads. Parameter > 600
is suggested.

ZHIDIHUAYUAN ***@***.***> 于2024年3月6日周三 21:46写道：

**Comment by ZHIDIHUAYUAN** [comment]
Thank you so much.
What about the suggested values of fragment_number_cutoff and connection_score_cutoff in step4.cluster_intramolecular?

**Comment by caochch** [comment]
use 2 at least for fragment_num_cutoff
and 0.01 at least for connection_score_cutoff

For both, a higher value corresponds to a lower false-positive rate.

ZHIDIHUAYUAN ***@***.***> 于2024年3月7日周四 20:54写道：

**Comment by ZHIDIHUAYUAN** [comment]
OK! Thank you very much!
